export const sanitizeOptions = {
  tagNames: [
    "p",
    "br",
    "strong",
    "em",
    "u",
    "s",
    "del",
    "ins",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "ul",
    "ol",
    "li",
    "code",
    "pre",
    "blockquote",
    "q",
    "hr",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    "div",
    "img",
    "figure",
    "figcaption",
    "span",
    "math",
    "annotation",
    "semantics",
  ],
  attributes: {
    "*": ["className", "style", "id"],
    a: ["href", "target", "rel", "title"],
    img: ["src", "alt", "width", "height", "loading"],
    th: ["colspan", "rowspan", "scope", "abbr"],
    td: ["colspan", "rowspan"],
    table: ["role"],
    span: ["className", "style"],
    math: ["*"],
    annotation: ["*"],
    semantics: ["*"],
  },
  // ADD THIS: Safelist secure network imagery protocols
  protocols: {
    href: ["http", "https", "mailto"],
    src: ["http", "https"], // Ensures https://cloudinary.com links are allowed
  },
};
